sudo: required

language: python
python:
  - "3.6"  # required, otherwise conda will try to clash with py2 packages

before_install:
  - export PACKAGE_NAME=ngs_utils
  # Get and install anaconda (https://conda.io/docs/travis.html)
  - wget -nv https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a  # Useful for debugging any issues with conda
  - conda config --set always_yes true
  - conda config --set anaconda_upload no

install:
  - conda install -q python=$TRAVIS_PYTHON_VERSION pip requests conda-build jinja2 anaconda-client click
  # Building package
  - conda build -c vladsaveliev -c bioconda -c conda-forge deploy/conda_package/${PACKAGE_NAME}
  - conda install -c vladsaveliev -c bioconda -c conda-forge --use-local ${PACKAGE_NAME}

script:
  - python -c "from ngs_utils import file_utils"
  - python -c "from ngs_utils import reference_data"
  - python -c "import tab_utils"

deploy:
  # Deploy to Anaconda.org
  - provider: script
    script: ./deploy/deploy_anaconda.sh $PACKAGE_NAME $ANACONDA_TOKEN
    on:
      tags: true
    skip_cleanup: true

